import { AccountingPolicy, TemplateItem } from "./types";

// --- 3. STATEMENT STRUCTURE TEMPLATES (FIXED) ---
export const BALANCE_SHEET_STRUCTURE: TemplateItem[] = [
  {
    key: "bs-assets",
    label: "ASSETS",
    isGrandTotal: true,
    children: [
      {
        key: "bs-assets-nc",
        label: "Non-current assets",
        isSubtotal: true,
        children: [
          {
            key: "bs-assets-nc-ppe",
            label: "Property, plant and equipment",
            note: 3,
          },

          {
            key: "bs-assets-nc-rou",
            label: "Right of use asset",
            note: "4a",
            noteLink: 4,
          },
          {
            key: "bs-assets-nc-cwip",
            label: "Capital work-in-progress",
            note: "3c",
            noteLink: 3,
          },
          {
            key: "bs-assets-nc-intangible",
            label: "Other Intangible assets",
            note: "4b",
            noteLink: 4,
          },

          {
            key: "bs-assets-nc-otherintangible",
            label: "Intangible assets under development",
            note: "4c",
            noteLink: 4,
          },

          {
            key: "bs-assets-nc-fin",
            label: "Financial Assets",
            isSubtotal: true,
            children: [
              { key: "bs-assets-nc-fin-loan", label: "Loans", note: 5 },
              {
                key: "bs-assets-nc-fin-other",
                label: "Other financial assets",
                note: 6,
              },
            ],
          },
          {
            key: "bs-assets-nc-dta",
            label: "Deferred tax assets (net)",
            note: 34,
            keywords: ["deferred tax assets (net)"],
          },
          {
            key: "bs-assets-nc-fin-income",
            label: "Income Tax asset(net)",
            note: 7,
          },
          {
            key: "bs-assets-nc-other",
            label: "Other non-current assets",
            note: 10,
          },
        ],
      },
      {
        key: "bs-assets-c",
        label: "Current assets",
        isSubtotal: true,
        children: [
          { key: "bs-assets-c-inv", 
            label: "Inventories", 
            note: 8 
          },
          {
            key: "bs-assets-c-fin",
            label: "Financial Assets",
            isSubtotal: true,
            children: [
              {
                key: "bs-assets-c-fin-tr",
                label: "Trade receivables",
                note: 9,
              },
              {
                key: "bs-assets-c-fin-cce",
                label: "Cash and cash equivalents",
                note: 11,
              },
              {
                key: "bs-assets-c-fin-bank",
                label: " Bank balances other than above",
                note: 11,
              },
              { key: "bs-assets-c-fin-loans", label: "Loans", note: 5 },
              {
                key: "bs-assets-c-fin-other",
                label: "Other financial assets",
                note: 6,
              },
            ],
          },
          { key: "bs-assets-c-other", label: "Other current assets", note: 10 },
        ],
      },
    ],
  },
  {
    key: "bs-eq-liab",
    label: "EQUITY AND LIABILITIES",
    isGrandTotal: true,
    formula: ["eq", "+", "liab-nc", "+", "liab-c"],
    children: [
      {
        key: "bs-eq",
        label: "Equity",
        isSubtotal: true,
        children: [
          {
            key: "bs-eq-captial",
            label: "Equity share capital",
            note: 12,
            keywords: ["equity"],
          },
          { key: "bs-eq-other", label: "Other equity", note: 13 },
        ],
      },
      {
        key: "bs-liab-nc",
        label: "Non-current liabilities",
        isSubtotal: true,
        children: [
          {
            key: "bs-liab-nc-fin",
            label: "Financial Liabilities",
            isSubtotal: true,
            children: [
              {
                key: "bs-liab-nc-fin-borrow",
                label: "Lease Liabilities",
                note: 29,
              },
            ],
          },
          { key: "bs-liab-nc-prov", label: "Provisions", note: 17 },
        ],
      },
      {
        key: "bs-liab-c",
        label: "Current liabilities",
        isSubtotal: true,
        children: [
          {
            key: "bs-liab-c-fin",
            label: "Financial Liabilities",
            isSubtotal: true,
            children: [
              {
                key: "bs-liab-c-fin-liability",
                label: "Lease Liabilities",
                note: 29,
              },
              {
                key: "bs-liab-c-fin-tp",
                label: "Trade payables",
                isSubtotal: true,
                children: [
                  {
                    key: "bs-liab-c-fin-enterprises",
                    label:
                      " Total outstanding dues of micro enterprises and small enterprises",
                    note: 14,
                  },
                  {
                    key: "bs-liab-c-fin-creators",
                    label:
                      " Total outstanding dues of creditors other than micro enterprises and small enterprises",
                    note: 14,
                  },
                  {
                    key: "bs-liab-c-fin-enterprises-other",
                    label: "Other Financial liabilities",
                    note: 15,
                  },
                ],
              },
            ],
          },
          {
            key: "bs-liab-c-other",
            label: "Other current liabilities",
            note: 16,
          },
          { key: "bs-liab-c-prov", label: "Provisions", note: 17 },
          {
            key: "bs-liab-c-tax",
            label: "Income tax liabilities (net)",
            note: "7a",
            noteLink: 7,
          },
        ],
      },
    ],
  },
];
export const INCOME_STATEMENT_STRUCTURE: TemplateItem[] = [
  {
    key: "is-income",
    label: "INCOME",
    id: "totalIncome",
    isSubtotal: true,
    children: [
      { key: "is-rev-ops", label: "Revenue from operations", note: 18 },
      { key: "is-other-inc", label: "Other income", note: 19 },
    ],
  },
  {
    key: "is-expenses",
    label: "EXPENSES",
    id: "totalExpenses",
    isSubtotal: true,
    children: [
      {
        key: "is-exp-mat",
        label: "Cost of materials consumed",
        note: "20a",
        noteLink: 20,
      },
      {
        key: "is-exp-pur",
        label: "Purchase of traded goods",
        note: "20b",
        noteLink: 20,
      },
      {
        key: "is-exp-inv",
        label: "Changes in inventories of work-in-progress and stock-in-trade",
        note: "20c",
        noteLink: 20,
      },
      { key: "is-exp-emp", label: "Employee benefits expense", note: 21 },
      { key: "is-exp-fin", label: "Finance cost", note: 22 },
      {
        key: "is-exp-dep",
        label: "Depreciation and amortisation expense",
        note: 23,
      },
      { key: "is-exp-oth", label: "Other expenses", note: 24 },
    ],
  },
  {
    key: "is-pbeit",
    label: "PROFIT BEFORE EXCEPTIONAL ITEM & TAXES",
    id: "pbeit",
    isSubtotal: true,
    formula: ["totalIncome", "-", "totalExpenses"],
  },
  {
    key: "is-except",
    label: "Exceptional Income",
    id: "exceptional",
    keywords: ["Other income", "Exceptional Income"],
  },
  {
    key: "is-pbt",
    label: "PROFIT BEFORE TAX",
    id: "pbt",
    isSubtotal: true,
    formula: ["pbeit", "+", "exceptional"],
  },
  {
    key: "is-tax",
    label: "TAX EXPENSE:",
    id: "totalTax",
    isSubtotal: true,
    children: [
      { key: "is-tax-curr", label: "Current tax", note: 34 },
      { key: "is-tax-def", label: "Deferred tax", note: 34 },
    ],
  },
  {
    key: "is-pat",
    label: "PROFIT FOR THE YEAR",
    id: "pat",
    isGrandTotal: true,
    formula: ["pbt", "-", "totalTax"],
  },
  {
    key: "is-oci",
    label: "Other comprehensive income",
    id: "comp-income",
    isSubtotal: true,
    children: [
      {
        key: "is-oci-profitorloss",
        label: "i) Items that will not be reclassified to profit or loss:",
      },
      {
        key: "is-oci-remesure",
        label: "   - Remeasurement on the defined benefit liabilities",
        note: 28,
      },
      {
        key: "is-oci-tax",
        label:
          "ii) Income tax relating to items not to be reclassified to profit or loss",
        note: 34,
      },
      // {
      //   key: "is-oci-total",
      //   label: "Other comprehensive income for the year",
      //   isSubtotal: true,
      // },
    ],
  },
  // {
  //   key: "is-pat",
  //   label: "Other comprehensive income for the year",
  //   id: "pat",
  //   isGrandTotal: true,
  //   formula: ["pbt", "-", "totalTax"],
  // },
  {
    key: "is-total-comprehensive",
    label: "Total comprehensive income for the year",
    id: "totalComprehensive",
    isGrandTotal: true,
    formula: ["pat", "+", "comp-income"],
  },
  {
    key: "is-eps",
    label: "Earnings per equity share",
    isSubtotal: true,
    children: [
      {
        key: "is-eps-value",
        label: "- Basic and diluted (in Rs.)",
        note: 32,
      },
    ],
  },
];
export const CASH_FLOW_STRUCTURE: TemplateItem[] = [
  {
    key: "cf-op",
    label: "A. Cash flow from operating activities",
    formula: ["totalA", "+", 0],
    isSubtotal: true,
    children: [
      {
        key: "cf-op-pro",
        label: "Profit for the year",
        id: "pro",
        //isSubtotal: true,
        //isEditableRow: true,
      }, // This will be populated from income statement PAT
      {
        key: "cf-op-sub",
        label: "Adjustments for:",
        id: "sub",
        children: [
          { key: "cf-op-sub-tax", label: "Tax Expense", note: 34, id: "tax" },
          {
            key: "cf-op-sub-dep",
            label: "Depreciation and amortisation",
            note: 23,
            id: "dep",
          },
          {
            key: "cf-op-sub-prov",
            label: "Provision/ Liabilities no longer required written back",
            id: "prov",
            isEditableRow: true,
          },
          {
            key: "cf-op-sub-interest",
            label: "Interest Income from bank deposits and financial assets",
            note: 19,
            id: "in",
          },
          {
            key: "cf-op-sub-interest-2",
            label: "Interest Expense on lease liabilities",
            note: 22,
            id: "in2",
          },
          {
            key: "cf-op-sub-prov-2",
            label:
              "Provision for doubtful trade receivables/(provision written back) (net)",
            note: 24,
            id: "prov2",
          },
          {
            key: "cf-op-sub-loss",
            label: "Loss on fixed assets sold / scrapped / written off ",
            note: 24,
            id: "loss",
          },
          {
            key: "cf-op-sub-prov-3",
            label: "Provision for expected loss on construction contracts ",
            note: 24,
            id: "prov3",
          },
          {
            key: "cf-op-sub-prov-4",
            label: "Provision for expected loss on onerous contracts ",
            note: 24,
            id: "prov4",
          },
          {
            key: "cf-op-sub-loss-1",
            label: "Net unrealised exchange (gain)/loss ",
            id: "loss2",
            isEditableRow: true,
          },
        ],
      },

      {
        key: "cf-op-profit",
        label: "Operating profit before working capital changes",
        isSubtotal: true,
        id: "profit",
        // isEditableRow: true,
        formula: [
          "pro",
          "+",
          "tax",
          "+",
          "dep",
          "+",
          "prov",
          "+",
          "in",
          "+",
          "in2",
          "+",
          "prov2",
          "+",
          "loss",
          "+",
          "prov3",
          "+",
          "prov4",
          "+",
          "loss2",
        ],
      },
      {
        key: "cf-op-mov",
        label: "Movements in working capital",
        isSubtotal: true,
        children: [
          {
            key: "cf-op-mov-inv",
            label: "Decrease/(Increase) in inventories",
            id: "inv",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-rec",
            label: "(Increase)/decrease in trade receivables",
            id: "rec",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-short",
            label: "Decrease/(Increase) in short-term loans",
            id: "short",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-nonfinancial",
            label: "Decrease/(Increase) in non-current other financial assets",
            id: "nonfinancial",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-nonasset",
            label: "Decrease/(Increase) in other non-current assets",
            id: "nonasset",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-long",
            label: "Decrease/(Increase) in long-term loans",
            id: "long",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-financial",
            label: "Decrease/(Increase) in current other financial assets",
            id: "financial",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-current",
            label: "Decrease/(Increase) in other current assets",
            id: "current",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-pay",
            label: "Increase/(decrease) in trade payables",
            id: "pay",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-currentlib",
            label: "Increase/(Decrease) in other current liabilities",
            id: "currentlib",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-otherlib",
            label: "Increase/(Decrease) in other Current financial liabilities",
            id: "otherlib",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-long-prov",
            label: "Increase/(Decrease) in Long-term provisions",
            id: "prov",
            isEditableRow: true,
          },
          {
            key: "cf-op-mov-short-prov",
            label: "Increase/(Decrease) in short-term provisions",
            id: "prov2",
            isEditableRow: true,
          },
        ],
      },
      {
        key: "cf-op-cgo",
        label: "Cash generated from operations",
        isSubtotal: true,
        id: "cgo",
        //isEditableRow: true,
        formula: [
          "profit",
          "+",
          "inv",
          "+",
          "rec",
          "+",
          "short",
          "+",
          "nonfinancial",
          "+",
          "nonasset",
          "+",
          "long",
          "+",
          "financial",
          "+",
          "current",
          "+",
          "pay",
          "+",
          "currentlib",
          "+",
          "otherlib",
          "+",
          "prov",
          "+",
          "prov2",
        ],
      },
      {
        key: "cf-op-direct-tax",
        label: "Direct taxes paid (net of refunds)",
        id: "tax",
        isEditableRow: true,
      },
      {
        key: "cf-op-total",
        label: "Net cash generated from operations (A)",
        isSubtotal: true,
        formula: ["cgo", "+", "tax"],
        id: "totalA",
      },
    ],
  },
  {
    key: "cf-inv",
    label: "B. Cash flow from investing activities",
    isSubtotal: true,
    formula: ["totalB", "+", 0],
    children: [
      {
        key: "cf-inv-capex",
        label:
          "Purchase of property, plant and equipment, including CWIP and capital advances ",
        id: "capex",
        isEditableRow: true,
        children: [
          {
            key: "cf-inv-capex-ppe",
            label: "Proceeds from sale of property, plant and equipment",
            id: "ppe",
            isEditableRow: true,
          },
          {
            key: "cf-inv-capex-cce",
            label:
              "Other bank balances not considered as cash and cash equivalents",
            id: "cce",
            isEditableRow: true,
          },
          {
            key: "cf-inv-capex-interest",
            label: "Interest received",
            id: "inter",
            isEditableRow: true,
          },
        ],
      },
      {
        key: "cf-op-cgo-total",
        label: "Net cash (used in) from investing activities (B)",
        isSubtotal: true,
        id: "totalB",
        //isEditableRow: true,
        formula: ["capex", "+", "ppe", "+", "cce", "+", "inter"],
      },
    ],
  },
  {
    key: "cf-fin",
    label: "C. Cash flow from financing activities",
    isSubtotal: true,
    formula: ["totalC", "+", 0],
    children: [
      {
        key: "cf-fin-lib",
        label: "Payment Towards Lease Liabilities ",
        id: "lib",
        isEditableRow: true,
      },
      {
        key: "cf-fin-dividend",
        label: "Payment of Dividend",
        id: "div",
        isEditableRow: true,
      },
      {
        key: "cf-fin-total",
        label: "Net cash used in financing activities (C)",
        isSubtotal: true,
        formula: ["lib", "+", "div"],
        id: "totalC",
      },
    ],
  },

  {
    key: "cf-foreign",
    id: "foreign",
    label:
      "Effect of exchange differences on restatement of foreign currency cash and cash equivalents",
    isSubtotal: true,
    isEditableRow: true,
  },
  {
    key: "cf-net-total",
    label: "Net increase in cash and cash equivalents (A+B+C)",
    isSubtotal: true,
    id: "net-total",
    formula: ["totalA", "+", "totalB", "+", "totalC"],
    children: [
      {
        key: "cf-net-total-prev",
        label: "Cash and cash equivalents at the beginning of the year",
        isEditableRow: true,
        id: "cashbegin",
      },
    ],
  },
  {
    key: "cf-cce-prev",
    label: "Cash and cash equivalents at the end of the year (Refer note 11)",
    isSubtotal: true,
    //isEditableRow: true,
    formula: ["net-total", "+", "cashbegin", "+", "foreign"],
  },
  {
    key: "cf-cce",
    label: "Components of cash and cash equivalents",
    isSubtotal: true,
    formula: ["tce", "+", 0],
    children: [
      { key: "cf-cce-cih", label: "Cash in hand", id: "cih" },
      { key: "cf-cce-bank", label: "Balances with banks" },
      { key: "cf-cce-current", label: "  (i) In current accounts", id: "cce" },
      { key: "cf-cce-eefc", label: "  (ii) In EEFC accounts", id: "cce-eefc" },
      {
        key: "cf-cce-fixed",
        label: "  (iii) Fixed deposits with maturity less than 3 months",
        id: "fixed",
      },
      {
        key: "cf-cce-total",
        label: "Total cash and cash equivalents",
        isSubtotal: true,
        id: "tce",
        formula: ["cih", "+", "cce", "+", "cce-eefc", "+", "fixed"],
      },
    ],
  },
];
export const ACCOUNTING_POLICIES_CONTENT: AccountingPolicy[] = [
  {
    title: "1. General Information",
    text: [
      "The Company is engaged in the manufacturing of industrial automation systems and trading of related products and customer services activities in India. It also provides certain technical services overseas.",
    ],
  },
  {
    title: "2. Summary of material accounting policies",
    text: [
      "a) Statement of compliance",
      'These financial statements have been prepared in accordance with Indian Accounting Standards ("Ind AS") notified under the Companies (Indian Accounting Standards) Rules, 2015 and relevant amendment rules issued thereafter.',
      "Accounting policies have been consistently applied except where a newly issued accounting standard is initially adopted or a revision to an existing accounting standard requires a change in the accounting policy hitherto in use.",
      "b) Basis of accounting and presentation",
      "The financial statements have been prepared on the historical cost basis except for certain financial instruments that are measured at fair values at the end of each reporting period, as explained in the accounting policies below.",
      "Historical cost is generally based on the fair value of the consideration given in exchange for services.",
      "Fair value is the price that would be received to sell an asset or paid to transfer a liability in an orderly transaction between market participants at the measurement date, regardless of whether that price is directly observable or estimated using another valuation technique. In estimating the fair value of an asset or a liability, the Company takes into account the characteristics of the asset or liability if market participants would take those characteristics into account when pricing the asset or liability at the measurement date. Fair value for measurement and/or disclosure purposes in these standalone financial statements is determined on such a basis, except for measurements that have some similarities to fair value but are not fair valued, such as value in use quantification as per Ind AS 36.",
      "In addition, for financial reporting purposes, fair value measurements are categorised into Level 1, 2, or 3 based on the degree to which the inputs to the fair value measurements are observable and the significance of the inputs to the fair value measurement in its entirety, which are described as follows:",
      "Level 1 inputs are quoted prices (unadjusted) in active markets for identical assets or liabilities that the entity can access at the measurement date;",
      "Level 2 inputs are inputs, other than quoted prices included within Level 1, that are observable for the asset or liability, either directly or indirectly; and",
      "Level 3 inputs are unobservable inputs for the asset or liability.",
      "c) Use of estimates and judgements",
      "The following are significant management judgements and estimates in applying the accounting policies of the Company that have the most significant effect on the amounts recognized in the financial statements or that have a significant risk of causing a material adjustment to the carrying amounts of assets and liabilities within the next financial year.",
      "The preparation of the financial statements in conformity with the recognition and measurement principals of Ind AS requires the Management to make estimates and assumptions considered in the reported amounts of assets and liabilities and disclosure relating to contingent liabilities as at the date of financial statements and the reported amounts of income and expenditure during the reported year. The Management believes that the estimates used in preparation of the financial statements are prudent and reasonable. Future results could differ due to these estimates and the differences between the actual results and the estimates are recognised in the periods in which the results are known / materialise.",
      "Useful lives of property, plant and equipment",
      "The Company reviews the useful life of property, plant and equipment at the end of each reporting period. This reassessment may result in change in depreciation expense in future periods.",
      "Provision for income tax and valuation of deferred tax assets",
      "The Company's major tax jurisdiction is India. Significant judgement is involved in determining the provision for income taxes, including the amount expected to be paid or recovered in connection with uncertain tax positions.",
      "The extent to which deferred tax assets can be recognised is based on an assessment of the probability that future taxable income will be available against which the deductible temporary differences and tax loss carry forward can be utilised.",
      "Recoverability of advances / receivables",
      "At each balance sheet date, based on historical default rates observed over expected life, the management assesses the expected credit loss on outstanding receivables and advances.",
      "Employee Benefits",
      "The present value of the defined benefit obligations depends on a number of factors that are determined on an actuarial basis using a number of assumptions. The assumptions used in determining the net cost/(income) for pensions include the discount rate.",
      "Any changes in these assumptions will impact the carrying amount of pension obligations. The Company determines the appropriate discount rate at the end of each year. This is the interest rate that should be used to determine the present value of estimated future cash outflows expected to be required to settle the pension obligations. In determining the appropriate discount rate, ahe Company considers the interest rates of Government securities that are denominated in the currency in which the benefits will be paid and that have terms to maturity approximating the terms of the related pension obligation. Other key assumptions for pension obligations are based in part on current market conditions.",
      "Also refer Revenue Recognition (Note 2(i))",
      "d) Current versus non-current classification",
      "The Company presents assets and liabilities in the balance sheet based on current/ non-current classification.",
      "An asset is treated as current when it is:",
      "- Expected to be realized or intended to be sold or consumed in normal operating cycle;",
      "- Held primarily for the purpose of trading;",
      "- Expected to be realized within twelve months after the reporting period, or",
      "- Cash or cash equivalent unless restricted from being exchanged or used to settle a liability for at least twelve months after the reporting period",
      "All other assets are classified as non-current.",
      "A liability is current when:",
      "- It is expected to be settled in normal operating cycle;",
      "- It is held primarily for the purpose of trading;",
      "- It is due to be settled within twelve months after the reporting period, or",
      "- There is no unconditional right to defer the settlement of the liability for at least twelve months after the reporting period.",
      "All other liabilities are classified as non-current.",
      "The operating cycle is the time between the acquisition of assets for processing and their realization in cash and cash equivalents. The Company has evaluated and considered its operating cycle as 12 months.",
      "Deferred tax assets/ liabilities are classified as non-current assets/ liabilities.",
      "e) Property, plant and equipment",
      "Property, plant and equipment are stated at cost, less accumulated depreciation and impairment, if any. Costs directly attributable to acquisition are capitalised until the property, plant and equipment are ready for use, as intended by management.",
      "Advances paid towards the acquisition of property, plant and equipment outstanding at each balance sheet date is classified as capital advances under other non-current assets and the cost of assets not put to use before such date are disclosed under ‘Capital work-in-progress’. Subsequent expenditures relating to property, plant and equipment is capitalised only when it is probable that future economic benefits associated with these will flow to the company and the cost of the item can be measured reliably.",
      "The cost and related accumulated depreciation are eliminated from the financial statements upon sale or retirement of the asset and the resultant gains or losses are recognised in the Statement of Profit and Loss. Assets to be disposed off are reported at the lower of the carrying value or the fair value less cost to sell.",
      "The Company depreciates property, plant and equipment over their estimated useful lives using the straight-line method. The estimated useful lives of assets are as follows:",
      {
        type: "table",
        headers: ["", "Useful lives (in years)"],
        rows: [
          ["Building", "30 to 60"],
          ["Vehicles*", "6"],
          ["Plant and Machinery*", "5 to 15"],
          ["Furniture and fixtures and office equipment's*", "2 to 10"],
        ],
      },
      "Leasehold improvements are amortised over the duration of the lease",
      "Assets costing less than ₹ 10,000 each are fully depreciated in the year of capitalisation",
      "* Based on an internal assessment, the management believes that the useful lives as given above represents the period over which management expects to use the assets. Hence, the useful lives for these assets is different from the useful lives as prescribed under Part C of Schedule II of the Companies Act, 2013.",
      "Properties in the course of construction for production, supply or administrative purposes are carried at cost, less any recognised impairment loss. Cost includes professional fees and, for qualifying assets, borrowing costs capitalised in accordance with the accounting policy. Such properties are classified to the appropriate categories of property, plant and equipment when completed and ready for intended use. Depreciation of these assets, on the same basis as other property assets, commences when the assets are ready for their intended use.",
      "The Company has evaluated the applicability of component accounting as prescribed under Ind AS 16 and Schedule II of the Companies Act, 2013, the management has not identified any significant component having different useful lives. Schedule II requires the Company to identify and depreciate significant components with different useful lives separately.",
      "Depreciation methods, useful lives and residual values are reviewed periodically and updated as required, including at each financial year end.",
      "Land is measured at cost. As no finite useful life for land can be determined, related carrying amounts are not depreciated.",
      "f) Intangible assets",
      "Intangible assets are recorded at the consideration paid for the acquisition of such assets and are carried at cost less accumulated amortisation and impairment. Advances paid towards the acquisition of intangible assets outstanding at each Balance Sheet date are disclosed as other non-current assets and the cost of intangible assets not ready for their intended use before such date are disclosed as intangible assets under development.",
      "Intangible assets are amortised over their estimated useful life as follows:",
      {
        type: "table",
        headers: ["Asset Category", "Useful lives (in years)"],
        rows: [["Computer Software", "3"]],
      },
      "Gains or losses arising from derecognition of an intangible asset are measured as the difference between the net disposal proceeds and the carrying amount of the asset and are recognised in the Statement of Profit and Loss when the asset is derecognised.",
      "The residual values, useful lives and methods of amortization of intangible assets are reviewed at each financial year end and adjusted prospectively, if appropriate.",
      "g) Impairment of property, plant and equipment and intangible assets",
      "At each reporting date, the Company assesses whether there is any indication that an asset may be impaired, based on internal or external factors. If any such indication exists, the Company estimates the recoverable amount of the asset or the cash generating unit. If such recoverable amount of the asset or cash generating unit to which the asset belongs is less than its carrying amount, the carrying amount is reduced to its recoverable amount. The reduction is treated as an impairment loss and is recognised in the Statement of Profit and Loss. If, at the reporting date there is an indication that a previously assessed impairment loss no longer exists, the recoverable amount is reassessed and the asset is reflected at the recoverable amount. Impairment losses previously recognised are accordingly reversed in the Statement of Profit and Loss.",
      "h) Inventories",
      "Inventories are valued at the lower of cost on weighted average basis and the net realisable value after providing for obsolescence and other losses, where considered necessary. Cost includes all charges in bringing the goods to the point of sale, including octroi and other levies, transit insurance and receiving charges. Work-in-progress and finished goods include appropriate proportion of overheads.",
      "i) Revenue recognition",
      "The Company applies Ind AS 115 “Revenue from Contracts with Customers”.",
      "The Company recognises revenue from contracts with customers when it satisfies a performance obligation by transferring promised goods or services to a customer. The revenue is recognised to the extent of transaction price allocated to the performance obligation satisfied. Performance obligation is satisfied over time when the transfer of control of asset (good or service) to a customer is done over time and in other cases, performance obligation is satisfied at a point in time. For performance obligation satisfied over time, the revenue recognition is done by measuring the progress towards complete satisfaction of performance obligation. The progress is measured in terms of a proportion of actual cost incurred to-date, to the total estimated cost attributable to the performance obligation.",
      "Transaction price is the amount of consideration to which the Company expects to be entitled in exchange for transferring good or service to a customer excluding amounts collected on behalf of a third party. Variable consideration is estimated using the expected value method or most likely amount as appropriate in a given circumstance. Payment terms agreed with a customer are as per business practice and there is no financing component involved in the transaction price. Incremental costs of obtaining a contract, if any, and costs incurred to fulfil a contract are amortised over the period of execution of the contract in proportion to the progress measured in terms of a proportion of actual cost incurred to-date, to the total estimated cost attributable to the performance obligation.",
      "Significant judgments are used in:",
      "1. Determining the revenue to be recognised in case of performance obligation satisfied over a period of time; revenue recognition is done by measuring the progress towards complete satisfaction of performance obligation. The progress is measured in terms of a proportion of actual cost incurred to-date, to the total estimated cost attributable to the performance obligation. Judgement is involved in determining the total estimated cost.",
      "2. Determining the expected losses, which are recognised in the period in which such losses become probable based on the expected total contract cost as at the reporting date.",
      "(i) Revenue from operations",
      "Revenue presented is exclusive of goods and service tax (GST). Revenue also includes adjustments made towards liquidated damages and variation wherever applicable. Escalation and other claims, which are not ascertainable/ acknowledged by customers are not taken into account.",
      "A . Revenue from sale of goods is recognised as follows:",
      "Revenue from sale of manufactured and traded goods is recognised when the control of the same is transferred to the customer and it is probable that the Company will collect the consideration to which it is entitled for the exchanged goods.",
      "B. Revenue from construction/project related activity is recognised as follows:",
      "1. Fixed price contracts: Contract revenue is recognised over time to the extent of performance obligation satisfied and control is transferred to the customer. Contract revenue is recognised at allocable transaction price which represents the cost of work performed on the contract plus proportionate margin, using the percentage of completion method. Percentage of completion is the proportion of cost of work performed to-date, to the total estimated contract costs.",
      "Impairment loss (termed as provision for construction contracts in the financial statements) is recognized in profit or loss to the extent the carrying amount of the contract asset exceeds the remaining amount of consideration that the company expects to receive towards remaining performance obligations (after deducting the costs that relate directly to fulfil such remaining performance obligations).",
      'For contracts where the aggregate of contract cost incurred to date plus recognised profits (or minus recognised losses as the case may be) exceeds the progress billing, the surplus is shown as contract asset and termed as “Unbilled Receivable”. For contracts where progress billing exceeds the aggregate of contract costs incurred to-date plus recognised profits (or minus recognised losses, as the case may be), the surplus is shown as contract liability and termed as"" Unearned revenue"". Amounts received before the related work is performed are disclosed in the Balance Sheet as contract liability and termed as “Advances from customer”. The amounts billed on customer for work performed and are unconditionally due for payment i.e. only passage of time is required before payment falls due, are disclosed in the Balance Sheet as trade receivables.',
      "Revenue from services",
      "Revenue from rendering of services is recognised over time as and when the customer receives the benefit of the company’s performance and the Company has an enforceable right to payment for services transferred. Unbilled revenue represents value of services performed in accordance with the contract terms but not billed.",
      "Interest income:",
      "Interest income is reported on an accrual basis using the effective interest method and is included under the head “other income” in the Statement of Profit and Loss.",
      "j) Employee benefits",
      "Expenses and liabilities in respect of employee benefits are recorded in accordance with Ind AS 19, Employee Benefits.",
      "Defined contribution plan",
      "The Company's contribution to provident fund, and employee state insurance scheme contributions are considered as defined contribution plans and are charged as an expense based on the amount of contribution required to be made and when services are rendered by the employees.",
      "Overseas social security",
      "The Company contributes to social security charges of countries to which the Company deputes its employees on employment or has permanent employees. The plans are defined contribution plan and contributions paid or payable is recognised as an expense in these periods in which the employee renders services in those respective countries.",
      "Defined benefit plan",
      "Gratuity",
      "The liability or asset recognised in the balance sheet in respect of defined benefit gratuity plans is the present value of the defined benefit obligation at the end of the reporting period less the fair value of plan assets (if any). The cost of providing benefits under the defined benefit plan is determined using the projected unit credit method.",
      "The present value of the defined benefit obligation denominated in ₹ is and determined by discounting the estimated future cash outflows by reference to market yields at the end of the reporting period on government bonds that have terms approximating to the terms of the related obligation.",
      "Service cost on the Company's defined benefit plan is included in employee benefits expense. Employee contributions, all of which are independent of the number of years of service, are treated as a reduction of service cost.",
      "Gains and losses through re-measurements of the defined benefit plans are recognized in other comprehensive income, which are not reclassified to profit or loss in a subsequent period. Further, as required under Ind AS compliant Schedule III, the Company transfers those amounts recognized in other comprehensive income to retained earnings in the statement of changes in equity and in the balance sheet.",
      "Short-term employee benefits",
      "The undiscounted amount of short-term employee benefits expected to be paid in exchange for the services rendered by employees are recognised during the year when the employees render the service. These benefits include performance incentive and compensated absences which are expected to occur within twelve months after the end of the period in which the employee renders the related service. The cost of such compensated absences is accounted as under :",
      "(a) in case of accumulated compensated absences, when employees render the services that increase their entitlement of future compensated absences; and",
      "(b) in case of non-accumulating compensated absences, when the absences occur.",
      "Long-term employee benefits",
      "Compensated absences which are not expected to occur within twelve months after the end of the period in which the employee renders the related service are recognised as a liability at the present value of the defined benefit obligation as at the Balance Sheet date less the fair value of the plan assets out of which the obligations are expected to be settled. Long Service Awards are recognised as a liability at the present value of the defined benefit obligation as at the Balance Sheet date.",
      "k) Leases",
      "I. Company as lessee",
      "The Company's lease asset classes primarily consist of leases for buildings. The Company, at the inception of a contract, assesses whether the contract is a lease or not lease. A contract is, or contains, a lease if the contract conveys the right to control the use of an identified asset for a time in exchange for a consideration. This policy has been applied to contracts existing and entered into on or after April 1, 2019.",
      "The Company recognises a right-of-use asset and a lease liability at the lease commencement date. The right-of-use asset is initially measured at cost, which comprises the initial amount of the lease liability adjusted for any lease payments made at or before the commencement date, plus any initial direct costs incurred and an estimate of costs to dismantle and remove the underlying asset or to restore the underlying asset or the site on which it is located, less any lease incentives received.",
      "The right-of-use asset is subsequently depreciated using the straight-line method from the commencement date to the end of the lease term.",
      "The lease liability is initially measured at the present value of the lease payments that are not paid at the commencement date, discounted using the  Company's incremental borrowing rate. It is remeasured when there is a change in future lease payments arising from a change in an index or rate, if there is a change in the Company's estimate of the amount expected to be payable under a residual value guarantee, or if the Company changes its assessment of whether it will exercise a purchase, extension or termination option. When the lease liability is remeasured in this way, a corresponding adjustment is made to the carrying amount of the right-of-use asset, or is recorded in profit or loss if the carrying amount of the right-of-use asset has been reduced to zero.",
      "The Company has elected not to recognise right-of-use assets and lease liabilities for short-term leases that have a lease term of 12 months or less . The Company recognises the lease payments associated with these leases as an expense over the lease term.",
      "II. Company as lessor",
      "The Company entered into leasing arrangements as a lessor for certain equipment to its customer. Leases for which the Company is a lessor are classified as finance or operating leases. Whenever the terms of the lease transfer substantially all the risks and rewards of ownership to the lessee, the contract is classified as a finance lease. All other leases are classified as operating leases.",
      "Rental income from operating leases is recognised on a straight-line basis over the term of the relevant lease. Initial direct costs incurred in negotiating and arranging an operating lease are added to the carrying amount of the leased asset and recognised on a straight-line basis over the lease term.",
      "Amounts due from lessees under finance leases are recognised as receivables at the amount of the Company's net investment in the leases. Finance lease income is allocated to accounting periods so as to reflect a constant periodic rate of return on the Company's net investment outstanding in respect of the leases.",
      "Subsequent to initial recognition, the Company regularly reviews the estimated unguaranteed residual value and applies the impairment requirements of Ind AS 109, recognising an allowance for expected credit losses on the lease receivables.",
      "Finance lease income is calculated with reference to the gross carrying amount of the lease receivables, except for credit-impaired financial assets for which interest income is calculated with reference to their amortised cost (i.e. after a deduction of the loss allowance).",
      "l) Foreign currency transactions",
      "Functional and presentation currency",
      "The functional currency of the Company is the Indian Rupee. These financial statements are presented in Indian Rupees (₹)",
      "Transactions and balances",
      "- Foreign currency transactions are translated into the functional currency using the exchange rates at the dates of the transactions. Foreign exchange gains and losses resulting from the settlement of such transactions and from the translation of monetary assets and liabilities denominated in foreign currencies at year end exchange rates are generally recognised in Statement of Profit or Loss. They are deferred in equity if they relate to qualifying cash flow hedges and qualifying net investment hedges or are attributable to part of the net investment in a foreign operation. A monetary item for which settlement is neither planned nor likely to occur in the foreseeable future is considered as a part of the entity’s net investment in that foreign operation.",
      "- Foreign exchange differences regarded as an adjustment to borrowing costs are presented in the Statement of Profit and Loss, within finance costs. All other foreign exchange gains and losses are presented in the Statement of Profit and Loss on a net basis within other gains/(losses).",
      "- Non-monetary items that are measured at fair value in a foreign currency are translated using the exchange rates at the date when the fair value was determined. Translation differences on assets and liabilities carried at fair value are reported as part of the fair value gain or loss.",
      "m) Borrowing costs",
      "Borrowing costs directly attributable to the acquisition, construction or production of an asset that necessarily takes a substantial period of time to get ready for its intended use or sale are capitalised as part of the cost of the asset. All other borrowing costs are expensed in the period in which they occur. Borrowing costs consist of interest and other costs that an entity incurs in connection with the borrowing of funds. Borrowing cost also includes exchange differences to the extent regarded as an adjustment to the borrowing costs.",
      "n) Income taxes",
      "Income tax expense comprises current and deferred income tax. Current and deferred tax is recognised in the Statement of Profit and Loss, except to the extent that it relates to items recognised in other comprehensive income or directly in equity. In this case, the tax is also recognised in other comprehensive income or directly in equity, respectively.",
      "Current income tax for current and prior periods is recognised at the amount expected to be paid to or recovered from the tax authorities, using the tax rates and tax laws that have been enacted or substantively enacted by the Balance Sheet date.",
      "Deferred tax is recognized on temporary differences at the balance sheet date between the tax bases of assets and liabilities and their carrying amounts for financial reporting purposes, except when the deferred income tax arises from the initial recognition of goodwill or an asset or liability in a transaction that is not a business combination and affects neither accounting nor taxable profit or loss at the time of the transaction.",
      "Deferred income tax assets are recognized for all deductible temporary differences, carry forward of unused tax credits and unused tax losses, to the extent that it is probable that taxable profit will be available against which the deductible temporary differences, and the carry forward of unused tax credits and unused tax losses can be utilized.",
      "The carrying amount of deferred tax assets is reviewed at each reporting date and reduced to the extent that it is no longer probable that sufficient taxable profit will be available to allow all or part of the deferred tax asset to be utilised. Unrecognised deferred tax assets are re-assessed at each reporting date and are recognised to the extent that it has become probable that future taxable profits will allow the deferred tax asset to be recovered.",
      "Deferred tax relating to items is recognised outside profit or loss (either in other comprehensive income or in equity). Deferred tax items are recognised in correlation to the underlying transaction either in other comprehensive income or directly in equity.",
      "Deferred income tax assets and liabilities are measured using tax rates and tax laws that have been enacted or substantively enacted by the Balance Sheet date and are expected to apply to taxable income in the years in which those temporary differences are expected to be recovered or settled. The effect of changes in tax rates on deferred income tax assets and liabilities is recognised as income or expense in the period that includes the enactment or the substantive enactment date. A deferred income tax asset is recognised to the extent that it is probable that future taxable profit will be available against which the deductible temporary differences and tax losses can be utilised. The Company offsets current tax assets and current tax liabilities, where it has a legally enforceable right to setoff the recognised amounts and where it intends either to settle on a net basis, or to realise the asset and settle the liability simultaneously.",
      "MAT payable for a year is charged to the statement of profit and loss as current tax. The Company recognizes MAT credit available as an asset only to the extent that there is convincing evidence that the Company will pay normal income tax during the specified period, i.e., the period for which MAT credit is allowed to be carried forward. In the year in which the Company recognizes MAT credit as an asset in accordance with the Guidance Note on Accounting for Credit Available in respect of Minimum Alternative Tax under the Income-tax Act, 1961, the said asset is created by way of credit to the statement of profit and loss and shown as ‘MAT Credit Entitlement’ under Deferred Tax. The Company reviews the same at each reporting date and writes down the asset to the extent the Company does not have convincing evidence that it will pay normal tax during the specified period.",
      "o) Provisions and contingencies",
      "Provisions",
      "A provision is recognised if, as a result of a past event, the Company has a present legal or constructive obligation that is reasonably estimable, and it is probable that an outflow of economic benefits will be required to settle the obligation. If the effect of the time value of money is material, provisions are determined by discounting the expected future cash flows at a pre-tax rate that reflects current market assessments of the time value of money and the risks specific to the liability. The increase in the provision due to the passage of time is recognised as interest expense.",
      "Contingent liabilities",
      "A contingent liability is a possible obligation that arises from past events whose existence will be confirmed by the occurrence or non-occurrence of one or more uncertain future events not wholly within the control of the Company or a present obligation that is not recognised because it is not probable that an outflow of resources will be required to settle the obligation or it cannot be measured with sufficient reliability. The Company does not recognise a contingent liability but discloses its existence in the financial statements.",
      "Contingent assets",
      "Contingent assets are neither recognised nor disclosed. However, when realisation of income is virtually certain, related asset is recognised.",
      "Onerous contracts",
      "Present obligations arising under onerous contracts are recognised and measured as provisions. An onerous contract is considered to exist where the Company has a contract under which the unavoidable costs of meeting the obligations under the contract exceed the economic benefits expected to be received from the contract.",
      "Provision for Product Support",
      "The estimated liability for product warranties is recorded when products are sold. These estimates are established using historical information on the nature, frequency and average cost of warranty claims and management estimates regarding possible future incidence based on corrective actions on product failures. The timing of outflows will vary as and when warranty claim will arise.  Generally, warranty ranges from 12 to 36 months.",
      "As per the terms of the contracts, the Company provides post-contract services / warranty support to some of its customers. The Company accounts for the post-contract support / provision for warranty on the basis of the information available with the management duly taking into account the current and past technical estimates.",
      "p) Financial instruments",
      "Financial assets and financial liabilities are recognised when the Company becomes a party to the contractual provisions of the instruments. Financial assets and financial liabilities are initially measured at fair value. Transaction costs that are directly attributable to the acquisition or issue of financial assets and financial liabilities (other than financial assets and financial liabilities at fair value through profit or loss) are added to or deducted from the fair value of the financial assets or financial liabilities, as appropriate, on initial recognition. Transaction costs directly attributable to the acquisition of financial assets or financial liabilities at fair value through profit or loss are recognised immediately in Statement of Profit and Loss.",
      "All recognised financial assets are subsequently measured in their entirety at either amortised cost or fair value, depending on the classification of the financial assets.",
      "a) Financial assets",
      "Cash and Cash equivalents",
      "Cash comprises cash on hand and demand deposits with banks. Cash equivalents are short-term balances (with an original maturity of three months or less from the date of acquisition), highly liquid investments that are readily convertible into known amounts of cash and which are subject to insignificant risk of changes in value. ",
      "Financial assets at amortised cost",
      "Financial assets are subsequently measured at amortised cost if these financial assets are held within a business model whose objective is to hold these assets in order to collect contractual cash flows and contractual terms of financial asset give rise on specified dates to cash flows that are solely payments of principal and interest on the principal amount outstanding.",
      "Financial Assets at fair value through other comprehensive Income (FVTOCI)",
      "Financial assets are measured at fair value through other comprehensive income if these financial assets are held within business model whose objective is achieved by both collecting contractual cash flows on specified dates that are solely payments of principal and interest on the principal amount outstanding and selling financial assets.",
      "Financial assets at fair value through profit or loss (FVTPL)",
      "Financial assets are measured at fair value through profit or loss unless it measured at amortised cost or fair value through other comprehensive income on initial recognition. The transaction cost directly attributable to the acquisition of financial assets and liabilities at fair value through profit or loss are immediately recognised in the Statement of Profit and Loss.",
      "Impairment and derecognition of financial assets:",
      "The Company derecognises a financial asset when the contractual rights to the cash flows from the asset expire, or when it transfers the financial asset and substantially all the risks and rewards of the ownership of the asset to another party. On derecognition of a financial asset in its entirety, the difference between the asset carrying amount and the sum of the consideration received and receivable is recognised in profit or loss.",
      "The Company applies expected credit loss model for recognising impairment loss on financial assets measured at amortised cost, trade receivables, other contractual rights to receive cash or other financial asset. The Company is identifying the specific amounts of financial assets which has become bad during the year and providing the credit loss.",
      "b) Financial liabilities and Equity:",
      "Financial liabilities at amortised cost",
      "Financial liabilities are measured at amortised cost using effective interest method. For trade and other payables maturing within one year from the Balance Sheet date, the carrying amounts approximate fair value due to the short maturity of these instruments.",
      "Equity Instrument:",
      "An equity instrument is a contract that evidences residual interest in the assets of the company after deducting all of its liabilities. Equity instruments recognised by the Company are recognised at the proceeds received net off direct issue cost.",
      "Derecognition of financial liabilities",
      "The Company derecognises financial liabilities when, and only when, the Company's obligations are discharged, cancelled or have expired. The difference between the carrying amount of the financial liability derecognised and the consideration paid and payable is recognised in profit or loss.",
      "Accounting Policy on Foreign Exchange Management",
      "The Company manages its exposure to foreign exchange rate risks through natural hedging and would enter into derivative contracts including foreign exchange forward contracts, if considered necessary. Derivatives are initially recognized at fair value on the date a derivative contract is entered into and are subsequently re-measured to their fair value at the end of each reporting period. The resulting gain or loss is recognized in the profit or loss.",
      "Offsetting of financial instruments",
      "Financial assets and financial liabilities are offset and the net amount is reported in the Balance Sheet if there is a currently enforceable legal right to offset the recognised amounts and there is an intention to settle on a net basis, to realise the assets and settle the liabilities simultaneously.",
      "q) Impairment of financial assets",
      "In accordance with Ind AS 109 Financial Instruments, the Company applies expected credit loss (ECL) model for measurement and recognition of impairment loss for financial assets.",
      "ECL is the difference between all contractual cash flows that are due to the Company in accordance with the contract and all the cash flows that the entity expects to receive (i.e., all cash shortfalls), discounted at the original EIR. When estimating the cash flows, an entity is required to consider:",
      "- All contractual terms of the financial instrument over the expected life of the financial instrument. However, in rare cases when the expected life of the financial instrument cannot be estimated reliably, then the entity is required to use the remaining contractual term of the financial instrument.",
      "- Cash flows from the sale of collateral held or other credit enhancements that are integral to the contractual terms.",
      "Trade receivables",
      "The Company applies approach permitted by Ind AS 109 Financial Instruments, which requires expected lifetime losses to be recognised from initial recognition of receivables.",
      "Other financial assets",
      "For recognition of impairment loss on other financial assets and risk exposure, the Company determines whether there has been a significant increase in the credit risk since initial recognition and if credit risk has increased significantly, impairment loss is provided.",
      "r) Fair value measurement",
      "Fair value is the price that would be received to sell an asset or paid to transfer a liability in an orderly transaction between market participants at the measurement date. The fair value measurement is based on the presumption that the transaction to sell the asset or transfer the liability takes place either:",
      "- In the principal market for the asset or liability, or",
      "- In the absence of a principal market, in the most advantageous market for the asset or liability",
      "The principal or the most advantageous market must be accessible by the Company.",
      "The fair value of an asset or a liability is measured using the assumptions that market participants would use when pricing the asset or liability, assuming that market participants act in their economic best interest.",
      "A fair value measurement of a non-financial asset takes into account a market participant’s ability to generate economic benefits by using the asset in its highest and best use or by selling it to another market participant that would use the asset in its highest and best use.",
      "The Company uses valuation techniques that are appropriate in the circumstances and for which sufficient data are available to measure fair value, maximising the use of relevant observable inputs and minimising the use of unobservable inputs.",
      "All assets and liabilities for which fair value is measured or disclosed in the financial statements are categorised within the fair value hierarchy, described as follows, based on the lowest level input that is significant to the fair value measurement as a whole:",
      "Level 1 - Quoted (unadjusted) market prices in active markets for identical assets or liabilities.",
      "Level 2 - Valuation techniques for which the lowest level input that is significant to the fair value measurement is directly or indirectly observable.",
      "Level 3 - Valuation techniques for which the lowest level input that is significant to the fair value measurement is unobservable.",
      "s) Cash and cash equivalents",
      "Cash and cash equivalents for the purpose of presentation in the statement of cash flows comprises of cash at bank and in hand, bank overdraft and short term highly liquid investments/ bank deposits with an original maturity of three months or less that are readily convertible to known amounts of cash and are subject to an insignificant risk of changes in value.",
      "t) Segment Reporting",
      "Operating segments are reported in a manner consistent with the internal reporting provided to the Chief Operating Decision Maker. The Company is engaged in the manufacturing of industrial automation system which broadly forms part of one product group and hence constitute a single business segment.",
      "u) Exceptional Items",
      "Exceptional items are disclosed separately in the financial statements where it is necessary to do so to provide further understanding of the financial performance of the Company. These are material items of income or expense that have to be shown separately due to their nature or incidence.",
      "v) Events after the reporting period.",
      "Adjusting events are events that provide further evidence of conditions that existed at the end of the reporting period. The financial statements are adjusted for such events before authorisation for issue.",
      "Non-adjusting events are events that are indicative of conditions that arose after the end of the reporting period. Non-adjusting events after the reporting date are not accounted, but disclosed.",
      "w) Earnings/ (Loss) per Share (EPS)",
      "Basic EPS are calculated by dividing the net profit or loss for the period attributable to equity shareholders by the weighted average number of equity shares outstanding during the period. Partly paid equity shares are treated as a fraction of an equity share to the extent that they are entitled to participate in dividends relative to a fully paid equity share during the reporting period. The weighted average number of equity shares outstanding during the period is adjusted for events such as bonus issue, bonus element in a rights issue to existing shareholders, share split and reverse share split (consolidation of shares)  that have changed the number of equity shares outstanding, without a corresponding change in resources.",
      "Diluted EPS amounts are calculated by dividing the profit attributable to equity holders of the Company (after adjusting for interest on the convertible preference shares, if any) by the weighted average number of equity shares outstanding during the year plus the weighted average number of equity shares that would be issued on conversion of all the dilutive potential equity shares into equity shares. Dilutive potential equity shares are deemed converted as of the beginning of the period, unless issued at a later date. Dilutive potential equity shares are determined independently for each period presented.",
      "x) Cash flow statement",
      "Cash flows are reported using the indirect method, whereby profit / (loss) before extraordinary items and tax is adjusted for the effects of transactions of non-cash nature and any deferrals or accruals of past or future cash receipts or payments. The cash flows from operating, investing and financing activities of the Company are segregated based on the available information.",
    ],
  },
];
